//@ts-check
const { test, expect } = require('@playwright/test')
const { OrangeHRMLoginPage } = require('../pages/OrangeHRMLoginPage')
const { EmployeeDetailsPage } = require('../pages/EmployeeDetailsPage')
test('Update employee Other ID', async ({ page }) => {
    const orangeHRMLoginPage = new OrangeHRMLoginPage(page)
    const employeeDetailsPage = new EmployeeDetailsPage(page)
    await orangeHRMLoginPage.pageNavigation()
    const heading = await orangeHRMLoginPage.pageHeading()
    await expect(heading).toBeVisible()
    await orangeHRMLoginPage.login('Admin', 'admin123')
    await expect(page).toHaveURL(/dashboard/)
    await employeeDetailsPage.clickPim()
    await expect(page).toHaveURL(/viewEmployeeList/)
    await expect(employeeDetailsPage.tableRow.first()).toBeVisible()
    await employeeDetailsPage.selectEmployee()
    await expect(employeeDetailsPage.heading).toContainText('Personal Details')
    await employeeDetailsPage.fillOtherId('2345')
    // await expect(employeeDetailsPage.otherID).toHaveValue('2345')
    await employeeDetailsPage.clickSaveButton()
    await expect(employeeDetailsPage.otherID).toHaveValue('2345')
})