const{test,expect} = require ('@playwright/test')
const {PracticeFormPage} = require('../pages/PracticeFormPage')
const studentData = require('../test-data/studentData')
test('practice form',async({page})=>{
    const practiceFormPage = new PracticeFormPage(page)
    const studentNameRow = practiceFormPage.tableVerify.filter({hasText: 'Student Name'})
    const studentEmailRow = practiceFormPage.tableVerify.filter({hasText:'Student Email'})
    const genderRow = practiceFormPage.tableVerify.filter({hasText:'Gender'})
    const mobileRow = practiceFormPage.tableVerify.filter({hasText:'Mobile'})
    await practiceFormPage.navigation()
    await expect(practiceFormPage.pageHeading).toBeVisible()
    await practiceFormPage.enterFirstName(studentData.firstname)
    await practiceFormPage.enterlastName(studentData.lastname)
    await practiceFormPage.enterEmail(studentData.email)
    await practiceFormPage.gender()
    await practiceFormPage.enterMobileNumber(studentData.mobile)
    await practiceFormPage.submit()
    await expect(practiceFormPage.verify).toContainText('Thanks for submitting the form')
    await expect(studentNameRow).toContainText(studentData.firstname)
    await expect(studentEmailRow).toContainText(studentData.email)
    await expect(genderRow).toContainText(studentData.gender)
    await expect(mobileRow).toContainText(studentData.mobile)
})